version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: cloud-ide-traefik
    restart: unless-stopped
    command:
      # Enable Docker provider
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=cloud-ide-network
      
      # Enable file provider for static configuration
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --providers.file.watch=true
      
      # Configure entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      
      # Enable automatic HTTPS redirect
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      
      # Configure Let's Encrypt (for production)
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@example.com}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.caserver=${ACME_CA_SERVER:-https://acme-staging-v02.api.letsencrypt.org/directory}
      
      # Enable API and dashboard
      - --api.dashboard=true
      - --api.insecure=${TRAEFIK_INSECURE:-false}
      
      # Configure logging
      - --log.level=${TRAEFIK_LOG_LEVEL:-INFO}
      - --accesslog=true
      
      # Configure metrics (optional)
      - --metrics.prometheus=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addServicesLabels=true
      
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard (only if insecure mode)
      
    volumes:
      # Docker socket for container discovery
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
      # Traefik configuration
      - ./traefik:/etc/traefik:ro
      
      # Let's Encrypt certificates storage
      - ./letsencrypt:/letsencrypt
      
      # Logs
      - ./logs/traefik:/var/log/traefik
      
    networks:
      - cloud-ide-network
      
    labels:
      # Enable Traefik for itself
      - traefik.enable=true
      
      # Dashboard routing
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN:-localhost}`)
      - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-dashboard.service=api@internal
      
      # Dashboard authentication (basic auth)
      - traefik.http.routers.traefik-dashboard.middlewares=traefik-auth
      - traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_AUTH:-admin:$$2y$$10$$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi}
      
      # Security headers middleware
      - traefik.http.middlewares.security-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.security-headers.headers.customrequestheaders.X-Forwarded-For=
      - traefik.http.middlewares.security-headers.headers.customrequestheaders.X-Real-IP=
      
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - ACME_EMAIL=${ACME_EMAIL:-admin@example.com}
      
networks:
  cloud-ide-network:
    external: true