CREATE TABLE "code-spectre_extension" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "code-spectre_extension_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"extensionId" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"version" varchar(50) NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"installedBy" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "code-spectre_extension_extensionId_unique" UNIQUE("extensionId")
);
--> statement-breakpoint
CREATE TABLE "code-spectre_ide_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "code-spectre_ide_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"repositoryId" integer NOT NULL,
	"branchName" varchar(255) NOT NULL,
	"containerId" varchar(255) NOT NULL,
	"containerUrl" varchar(500) NOT NULL,
	"status" varchar(50) DEFAULT 'running' NOT NULL,
	"lastAccessedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "ide_session_container_id_unique" UNIQUE("containerId")
);
--> statement-breakpoint
CREATE TABLE "code-spectre_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "code-spectre_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"repositoryId" integer NOT NULL,
	"canCreateBranches" boolean DEFAULT false NOT NULL,
	"branchLimit" integer DEFAULT 5 NOT NULL,
	"allowedBaseBranches" json DEFAULT '["main","develop"]'::json NOT NULL,
	"allowTerminalAccess" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "permission_user_repository_unique" UNIQUE("userId","repositoryId")
);
--> statement-breakpoint
CREATE TABLE "code-spectre_repository" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "code-spectre_repository_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"gitUrl" varchar(500) NOT NULL,
	"ownerId" integer NOT NULL,
	"deployKeyPublic" text,
	"deployKeyPrivate" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "repository_git_url_unique" UNIQUE("gitUrl")
);
--> statement-breakpoint
CREATE TABLE "code-spectre_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "code-spectre_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"githubId" varchar(255) NOT NULL,
	"githubUsername" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"role" varchar(50) DEFAULT 'user' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "code-spectre_user_githubId_unique" UNIQUE("githubId")
);
--> statement-breakpoint
ALTER TABLE "code-spectre_extension" ADD CONSTRAINT "code-spectre_extension_installedBy_code-spectre_user_id_fk" FOREIGN KEY ("installedBy") REFERENCES "public"."code-spectre_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "code-spectre_ide_session" ADD CONSTRAINT "code-spectre_ide_session_userId_code-spectre_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."code-spectre_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "code-spectre_ide_session" ADD CONSTRAINT "code-spectre_ide_session_repositoryId_code-spectre_repository_id_fk" FOREIGN KEY ("repositoryId") REFERENCES "public"."code-spectre_repository"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "code-spectre_permission" ADD CONSTRAINT "code-spectre_permission_userId_code-spectre_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."code-spectre_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "code-spectre_permission" ADD CONSTRAINT "code-spectre_permission_repositoryId_code-spectre_repository_id_fk" FOREIGN KEY ("repositoryId") REFERENCES "public"."code-spectre_repository"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "code-spectre_repository" ADD CONSTRAINT "code-spectre_repository_ownerId_code-spectre_user_id_fk" FOREIGN KEY ("ownerId") REFERENCES "public"."code-spectre_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "extension_extension_id_idx" ON "code-spectre_extension" USING btree ("extensionId");--> statement-breakpoint
CREATE INDEX "extension_enabled_idx" ON "code-spectre_extension" USING btree ("enabled");--> statement-breakpoint
CREATE INDEX "extension_installed_by_idx" ON "code-spectre_extension" USING btree ("installedBy");--> statement-breakpoint
CREATE INDEX "ide_session_user_idx" ON "code-spectre_ide_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "ide_session_repository_idx" ON "code-spectre_ide_session" USING btree ("repositoryId");--> statement-breakpoint
CREATE INDEX "ide_session_status_idx" ON "code-spectre_ide_session" USING btree ("status");--> statement-breakpoint
CREATE INDEX "ide_session_last_accessed_idx" ON "code-spectre_ide_session" USING btree ("lastAccessedAt");--> statement-breakpoint
CREATE INDEX "permission_user_idx" ON "code-spectre_permission" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "permission_repository_idx" ON "code-spectre_permission" USING btree ("repositoryId");--> statement-breakpoint
CREATE INDEX "repository_owner_idx" ON "code-spectre_repository" USING btree ("ownerId");--> statement-breakpoint
CREATE INDEX "repository_name_idx" ON "code-spectre_repository" USING btree ("name");--> statement-breakpoint
CREATE INDEX "user_github_id_idx" ON "code-spectre_user" USING btree ("githubId");--> statement-breakpoint
CREATE INDEX "user_email_idx" ON "code-spectre_user" USING btree ("email");--> statement-breakpoint
CREATE INDEX "user_role_idx" ON "code-spectre_user" USING btree ("role");